from importlib import import_module

_EXPORT_MODULES = {
    'CalcChainPlugin': 'calcchain_plugin_system.api',
    'CapabilityKey': 'calcchain_core.capabilities',
    'CapabilityOwner': 'calcchain_core.capabilities',
    'CapabilityRecord': 'calcchain_core.capabilities',
    'CapabilityRegistrar': 'calcchain_plugin_system.registrars',
    'CapabilityRegistry': 'calcchain_plugin_system.registrars',
    'DeclaredCapability': 'calcchain_plugin_system.metadata',
    'PLUGIN_ENV_LOCK_NAME': 'calcchain_plugin_system.environment_lock',
    'PLUGIN_API_VERSION': 'calcchain_plugin_system.api',
    'PLUGIN_DIAGNOSTIC_PHASES': 'calcchain_plugin_system.diagnostics',
    'PipInstaller': 'calcchain_plugin_system.environment',
    'PlannedCapabilityDeclaration': 'calcchain_plugin_system.activation_plan',
    'PluginActivationError': 'calcchain_plugin_system.errors',
    'PluginActivationPlan': 'calcchain_plugin_system.activation_plan',
    'PluginActivationPlanner': 'calcchain_plugin_system.activation_plan',
    'PluginCapabilityConflictError': 'calcchain_plugin_system.errors',
    'PluginCompatibilityError': 'calcchain_plugin_system.errors',
    'PluginContext': 'calcchain_plugin_system.api',
    'PluginDependencies': 'calcchain_plugin_system.metadata',
    'PluginDependencyError': 'calcchain_plugin_system.errors',
    'PluginDependencyPlan': 'calcchain_plugin_system.dependencies',
    'PluginDependencyPlanner': 'calcchain_plugin_system.dependencies',
    'PluginDiagnostic': 'calcchain_plugin_system.diagnostics',
    'PluginDiagnosticPhase': 'calcchain_plugin_system.diagnostics',
    'PluginDiscovery': 'calcchain_plugin_system.discovery',
    'PluginEnvLock': 'calcchain_plugin_system.environment_lock',
    'PluginEnvironment': 'calcchain_plugin_system.environment',
    'PluginEnvironmentManager': 'calcchain_plugin_system.environment',
    'PluginEntrypointError': 'calcchain_plugin_system.errors',
    'PluginError': 'calcchain_plugin_system.errors',
    'PluginImporter': 'calcchain_plugin_system.importer',
    'PluginManager': 'calcchain_plugin_system.manager',
    'PluginMetadata': 'calcchain_plugin_system.metadata',
    'PluginMetadataError': 'calcchain_plugin_system.errors',
    'PluginMetadataReader': 'calcchain_plugin_system.metadata',
    'PluginPackage': 'calcchain_plugin_system.metadata',
    'PluginRegistrationError': 'calcchain_plugin_system.errors',
    'PluginRepository': 'calcchain_plugin_system.repository',
    'PluginRuntimeSet': 'calcchain_plugin_system.api',
    'PluginSettings': 'calcchain_plugin_system.settings',
    'PluginSettingsStore': 'calcchain_plugin_system.settings',
    'PluginValidator': 'calcchain_plugin_system.metadata',
    'PublishedRef': 'calcchain_core.io.target',
    'ReportAdapter': 'calcchain_core.capabilities',
    'ReportContext': 'calcchain_core.reports',
    'ReportDescriptor': 'calcchain_core.reports',
    'ReportRegistrar': 'calcchain_plugin_system.registrars',
    'ReportRequest': 'calcchain_core.reports',
    'ReportResult': 'calcchain_core.reports',
    'RequirementRecord': 'calcchain_plugin_system.dependencies',
    'ResolvedDependencies': 'calcchain_plugin_system.environment',
    'RuntimeCapabilities': 'calcchain_core.capabilities',
    'SecretsAdapter': 'calcchain_core.capabilities',
    'SecretsContext': 'calcchain_core.capabilities',
    'SecretsRegistrar': 'calcchain_plugin_system.registrars',
    'SourceAdapter': 'calcchain_core.capabilities',
    'SourceContext': 'calcchain_core.capabilities',
    'SourceRegistrar': 'calcchain_plugin_system.registrars',
    'TargetAdapter': 'calcchain_core.capabilities',
    'TargetContext': 'calcchain_core.capabilities',
    'TargetRegistrar': 'calcchain_plugin_system.registrars',
    'WheelLock': 'calcchain_plugin_system.dependencies',
    'WheelLockEntry': 'calcchain_plugin_system.dependencies',
    'WheelLockReader': 'calcchain_plugin_system.dependencies',
    'WheelRecord': 'calcchain_plugin_system.dependencies',
    'activate_plugins': 'calcchain_plugin_system.bootstrap',
    'compute_env_hash': 'calcchain_plugin_system.dependencies',
    'create_plugin_context': 'calcchain_plugin_system.api',
    'read_plugin_env_lock': 'calcchain_plugin_system.environment_lock',
    'redact_secrets': 'calcchain_plugin_system.diagnostics',
    'verify_plugin_env_lock': 'calcchain_plugin_system.environment_lock',
    'verify_wheel_hashes': 'calcchain_plugin_system.dependencies',
    'write_plugin_env_lock': 'calcchain_plugin_system.environment_lock',
}

__all__ = sorted(_EXPORT_MODULES)


def __getattr__(name: str) -> object:
    try:
        module_name = _EXPORT_MODULES[name]
    except KeyError as exc:
        raise AttributeError(f'module {__name__!r} has no attribute {name!r}') from exc
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value
