[exec]
source_type = "svn"
url = "file:///C:/Users/PALypatnikov/Desktop/Projects/CalcChain/examples/test_repo/exec"
revision = 7

[[data]]
source_type = "local"
path = "C:\\Users\\PALypatnikov\\Desktop\\Projects\\CalcChain\\examples\\test_local_storage\\data\\UNIT_NAME"
rule_set = "DATARULES_1"

[[data]]
source_type = "svn"
url = "file:///C:/Users/PALypatnikov/Desktop/Projects/CalcChain/examples/test_repo/data/OTHER_UNIT_NAME"
revision = "HEAD"