title = "Startup configurations"

[exec]
    
    [exec.sapfir]
    
        [exec.sapfir.local]
        path = "some_path"

    [exec.rc]

        [exec.rc.svn]
	link = "some_link"
        revision = "HEAD"

