title = "Startup configurations"

[exec]
    
    [exec.sapfir]
    
        [exec.sapfir.svn]
        link = "some_link"
        revision = "HEAD"
        
        [exec.sapfir.local]
        path = "some_path"
 
