schema_version = "1.0"

[publish]
message = ""

[service_target]
type = "local"
path = "examples/manifest_import/service_publish"

[[targets]]
name = "Локальная папка результата"
type = "local"
path = "examples/manifest_import/imported_results"
rule_sets = ["outputs"]

[[targets]]
name = "Локальная папка результата"
type = "local"
path = "examples/manifest_import/imported_logs"
rule_sets = ["logs"]
