schema_version = "1.0"

[lock]
created_at = "2026-05-18T15:01:52.450139+00:00"
created_from = "build.toml"
build_toml_sha256 = "30cb006da6d26c845eeb261cef25f5917c8b885034b6a387e541300273ae01fe"

[build]
name = "test-workspace-case"
description = ""

[code]
name = "code"
version = ""

[code.source]
type = "local"
path = "D:\\AI_Coding\\CalcChain\\examples\\test_workspace\\sources\\code"

[[inputs]]
name = "input"

[inputs.source]
type = "local"
path = "D:\\AI_Coding\\CalcChain\\examples\\test_workspace\\sources\\input"
