target-version = "py312"

lint.select = [
    "F", "E", "W", "UP", "PL", "ANN", "FA", "COM", "PERF", "PTH",
    "ARG", "PD", "C4", "PYI", "SIM", "Q", "BLE", "RUF",
]

#extend-select = ["ALL"]

lint.ignore = [
    # -----------------------------------------------------------------
    "D", # pydocstyle
    "T20", # flake8-print
#    "ANN101", # flake8-annotations/missing-type-self
#    "ANN102", # flake8-annotations/missing-type-cls
#    "PD901", # pandas-vet/pandas-df-variable-name
    "SIM108", # flake8-simplify/if-else-block-instead-of-if-exp
    "RUF001", # Ruff-specific/ambiguous-unicode-character-string
    "RUF003", # Ruff-specific/ambiguous-unicode-character-comment
    "PLR0913", # Pylint/too-many-arguments
    # -----------------------------------------------------------------
    "RUF100" # COMMENT TO CHECK NOQA INSTRUCTIONS
    # -----------------------------------------------------------------
]

line-length = 99

lint.flake8-quotes.inline-quotes = "single"
lint.flake8-annotations.allow-star-arg-any = true
lint.flake8-annotations.suppress-dummy-args = true
lint.flake8-annotations.mypy-init-return = true
