schema_version = "1.0"

[lock]
created_at = "2026-06-14T21:19:35.176689+00:00"
created_from = "build.toml"
build_toml_sha256 = "702ee920d72d137eb61f8d6c82369dfc958dffc9da1ba79c23cf63387d9fb7ce"

[build]
name = "manifest-import-demo"
description = ""

[code]
name = "demo_solver"
version = "fdffe0c8dfbb8f593c6c6522073190f423698de1381290547ad55082a5ffaf8f"

[code.source]
type = "local"
path = "examples/manifest_import/code"

[[inputs]]
name = "input_a"

[inputs.source]
type = "local"
path = "examples/manifest_import/input_a"

[[inputs]]
name = "input_b"

[inputs.source]
type = "local"
path = "examples/manifest_import/input_b"
